### ISSUE TITLE
Accès Client - Page compte-clés - Statuts des transactions

### ISSUE THREAD

**Issue by lesateliersduroi** [TBoileau/key-privilege#123]
Actuellement dans la colonne Opération, je ne vois que 2 statuts : débit et achat.

Attention, en tant que client, voici les statuts qui doivent exister : 
- Débit (ok)
- Achat (pas ok) => Crédit (le client n'achète pas de clés ; c'est son adhérent qui le crédite).
- Rétrocession. C'est un débit mais ce sera à l'initiative de l'adhérent qui souhaite reprendre des clés à son client.
- Péremption. C'est ce qu'il faut afficher si le client a des clés qui sont arrivées à expiration.
- Geste commercial. C'est un crédit mais c'est pour moi une particularité à prendre en compte car si on catégorise du côté adhérent ce type de crédit, ce sera plus facile à suivre pour l'adhérent et le client.

**Comment by TBoileau** [comment]
@lesateliersduroi Je ne peux pas faire de distinction entre Débit et Rétrocession. Il n'y aura pas non plus de notion de péremption, on ne débite rien, on garde toujours l'historique, mais dans le calcul du solde, on ne garde que les clés dont la date d'expiration n'est pas dépassée. Même remarque pour gestion commerciale, ça ne sera pas possible. Si on doit faire à chaque fois des choses spécifiques on ne s'en sort pas. Il ne faut pas complexifier pour rien et la c'est le cas.

**Comment by lesateliersduroi** [comment]
Ah non, pas d'accord. En arrière-plan je suis ok pour dire qu'en simplifiant on a que des débits et des crédits mais les cas de figure listés (rétrocession, péremption, don) sont nécessaires d'un point de vue opérationnel. Il faut pouvoir les catégoriser (ou du moins les afficher) de la sorte car dans le suivi quotidien de nos opérations, on ne peut pas se contenter de 2 statuts. Ce n'est pas un détail, c'est important. Ces statuts ont déjà été gérés sur certains projets avec Gui (notamment sur efid) et ils sont très utiles.

**Comment by TBoileau** [comment]
Yes on peut gérer une désignation, mais dans les faits ça restera un débit et un crédit.

**Comment by lesateliersduroi** [comment]
On est ok. Une désignation pour typer les mouvements (qui restent en définitive soit un débit, soit un crédit).
