### ISSUE TITLE
Accès Client - Formulaire Demande de SAV

### ISSUE THREAD

**Issue by lesateliersduroi** [TBoileau/key-privilege#128]
L'objet du message peut être conservé.
Toutefois les informations sont insuffisantes pour traiter la demande. Il faudrait ajouter la référence/le libellé du produit sélectionné pour lequel le client fait sa demande de SAV. S'il y a plusieurs produits dans la commande, il nous faut être plus précis dans la demande qu'il va nous envoyer.
Sinon, il manque aussi des informations à réclamer au moment de sa demande et j'ai dû te lister dans nos précédents échanges : numéro de série de l'appareil, description de la panne observée, ajouter une pièce jointe... Fais moi signe si besoin sur le sujet pour qu'on se cale bien là-dessus.

**Comment by TBoileau** [comment]
@lesateliersduroi Je ne me rappelle pas avoir eu le détail d'un SAV. Peux tu me lister les informations dont tu as besoin.

**Comment by lesateliersduroi** [comment]
Jette un oeil à la maquette pour mobile que Tim t'a envoyé le 05 mars, il a bien illustré les attendus (notamment pour le SAV) : https://xd.adobe.com/view/7c88c830-7ea1-400e-979f-3a305b87acf3-29db/screen/d939578a-64bb-4c95-8581-a4fd528dc15d/
