### ISSUE TITLE
Accès Client - Mail(s) formulaire de demande de SAV

### ISSUE THREAD

**Issue by lesateliersduroi** [TBoileau/key-privilege#130]
Je n'ai pas pu vérifier si un mail  est bien envoyé quand je valide le formulaire de demande. A vérifier. 

En étant complet/gourmand sur ce mail, j'en ferai bien partir 2 différents : l'un pour nous évidemment, l'autre pour le user avec un message légèrement différent qui aurait pour but de lui confirmer la prise en compte de sa demande. 
Etant utilisateur de beaucoup de service de SAV, je sais que c'est rassurant après avoir complété une demande de SAV de savoir qu'elle sera prise en compte en recevant un mail. J'utilise généralement ce mail quand je n'ai pas de réponse depuis plusieurs jours pour me manifester aux gens à qui j'ai écrit.

**Comment by TBoileau** [comment]
Tout est gérer avec Zendesk en fait, donc tu reçois un email et l'utilisateur aussi.
