### ISSUE TITLE
Mes codes d'accès v/s Mon mot de passe

### ISSUE THREAD

**Issue by lesateliersduroi** [TBoileau/key-privilege#137]
- Ok pour forcer/obliger une adresse mail dans les informations personnelles. Indispensable pour gérer les oublis mot de passe ou encore le suivi d'expédition des lots
- Par contre, dans la partie Modification Mot de passe, ce serait utile de renommer en Modification Codes d'accès en laissant aussi la possibilité de modifier l'identifiant. Actuellement c'est l'adresse mail. On a régulièrement le cas où les gens nous demandent de changer leur mail car ce n'est pas le bon ou qu'ils ont changé leur email + je n'ai rien contre le fait qu'ils ne mettent pas de mail en identifiant... Le seul truc qu'il faut conserver de manière obligatoire c'est un mail renseigné

**Comment by TBoileau** [comment]
Non il ne faut pas pouvoir modifier MDP et email en même temps,; car si la personne veut modifier seulement son email, il sera forcé de modifier aussi son mot de passe, et du coup ça décourage pas mal, en terme d'UX, il faut toujours rendre la modification du mot de passe indépendante du reste.
Si je mets le mail en identifiant, c'est surtout qu'aujourd'hui, TOUS les sites fonctionnent comme ça, vouloir faire différent, c'est aussi se heurter plus facilement au "j'ai oublié mon identifiant", personne n'oubli son email

**Comment by lesateliersduroi** [comment]
Je suis d'accord avec tes commentaires mais ce que je garde en tête c'est la gestion des cas des clients où avec une seule et même adresse mail, nous devons parfois les affecter à un ou plusieurs rôles différents. 
Tous les sites ne fonctionnent pas sur la base d'un couple mail/mot de passe. Pour notre client Lidl, on a 4500 inscrits et 0 mail... Bref, j'ai envie effectivement que ce soit "simple et fonctionnel", mais je n'ai pas envie de me confronter à des cas de figure déjà rencontrés et de ne pas pouvoir les solutionner.
Sans parler du mail, je t'avais aussi donner l'exemple d'un cas d'accès particulièrement complexe à gérer. Ex : un seul accès pour le dirigeant des Ateliers du ROI mais là tu découvres que ce sont des co-gérants et qu'ils sont 2. Pouvoir gérer 2 accès distincts qui pointent sur un seul compte...

**Comment by TBoileau** [comment]
- [ ] Ajouter un champ unique "username" qui sera utilisé pour la connexion
- [ ] Rendre le champ "email" non unique

**Comment by TBoileau** [comment]
Oui mais sans email unique, tu ne peux pas avoir de fonctionnalité "Oubli de mot de passe". Ensuite, l'exemple de LIDL n'est pas vraiment la même chose, LIDL est un outil pour le terrain. Ici, chaque utilisateur doit pouvoir être autonome, ce qui n'est pas le cas de LIDL, puisque, si besoin, je vais voir mon responsable pour qu'il puisse faire une action sur mon compte, et ce genre de relation ne doit, à mon sens, surtout pas exister entre l'adhérent et le client.
Donc non, on ne peut pas avoir un email pour plusieurs comptes, et ce n'est pas qu'une question théorique, mais surtout technique. Sans email, pas d'oubli de mot de passe, on infantilise donc l'utilisateur en le forçant à contacter quelqu'un car il a oublié son mot de passe.
Attention à ne pas encore une fois vouloir en faire trop car on a eu 1 cas sur 1000 utilisateurs. On peut aussi cadrer les choses en imposant des règles.
