### ISSUE TITLE
Profil Commercial - Menu Clients à changer

### ISSUE THREAD

**Issue by lesateliersduroi** [TBoileau/key-privilege#142]
- La fonctionnalité de gestion des sociétés doit être exclusive au rôle Administrateur Adhérent. Il faut donc l'enlever pour les commerciaux.
- La fonctionnalité de gestion des accès doit avoir des privilèges réduits pour un commercial : 
* Enlever la possibilité de créer un accès (exclusif à l'admin)
* Dans le tableau de gestion des accès, je masquerai la colonne du commercial car c'est forcément tout le temps la même info qui est affichée.
* Dans les fonctionnalités en bout de ligne, il faut enlever la fonction Supprimer (exclusif à l'admin)
* Dans les fonctionnalités en bout de ligne, il faut renommer : Réinitialiser => Renvoyer un mot de passe et Log as => Voir son profil

**Comment by TBoileau** [comment]
Donc si je comprends bien, le commercial n'a qu'une fonctionnalité de visibilité avec quelques fonctionnalités comme :
- le reset
- le log as
Mais pas de :
- modification
- ajout
- suppression
réservé aux admins

**Comment by lesateliersduroi** [comment]
Tu as presque tout compris. Je laisserai la fonction "modification" pour le commercial.
