### ISSUE TITLE
Profil Commercial - Ajouter dans le menu clients un sous-menu Suivi des commandes Clients

### ISSUE THREAD

**Issue by lesateliersduroi** [TBoileau/key-privilege#145]
Actuellement on ne donne pas la possibilité aux commerciaux de visualiser le suivi des commandes de ses clients rattachés. 
Ce serait bien utile de lui ajouter un tableau pour que le commercial puisse répondre de lui-même à certaines questions de ses clients.

**Comment by TBoileau** [comment]
@lesateliersduroi Est-ce que je dois aussi étendre ça aux administrateurs, pour qu'ils puissent eux aussi voir toutes les commandes passées par leur client ?
