### ISSUE TITLE
Admin Adhérent - Mon compte - Gestion des accès adhérent

### ISSUE THREAD

**Issue by lesateliersduroi** [TBoileau/key-privilege#153]
Je ne comprends pas à quoi correspond la fonctionnalité "Gestion des accès adhérent" dans le bloc Mon profil Key Privilege ??

**Comment by TBoileau** [comment]
Il faut bien qu'un admin puisse ajouter un commercial ou un collaborateur

**Comment by lesateliersduroi** [comment]
Ok, c'est une histoire d'UX pour faire comprendre à un admin que c'est en passant par ce lien qu'il peut gérer ses collaborateurs. Ce n'est pas instinctif. Je comprends la fonctionnalité mais je vais réfléchir pour savoir s'il ne faut pas la mettre à un autre endroit. Je tilte du coup sur le menu "Clients" qui pourrait devenir "Accès" et avec un regroupement plus global des gestions des rôles du type : 
- Créer une société
- Gestion des informations sociétés
- Créer un accès utilisateur client
- Gestion des accès clients
- Créer un accès collaborateur
- Gestion des accès de mon entreprise

**Comment by TBoileau** [comment]
ok nice
