### ISSUE TITLE
Admin Adhérent - Option Autoriser le client à saisir manuellement son adresse de livraison

### ISSUE THREAD

**Issue by lesateliersduroi** [TBoileau/key-privilege#161]
Pour moi, l'option n'est pas placée au bon endroit.
Je m'explique : elle devrait être au niveau de la création d'un accès et non pas à la création d'une société.
Actuellement, on a des sociétés comme IDLP qui autorisent certains clients à se faire livrer directement et qui ne le font pas pour le reste de leurs clients.
Du coup, pour tester cette fonctionnalité, je m'attendais à la retrouver dans le menu Modifier d'un accès client.

**Comment by TBoileau** [comment]
Comme tu le dis `qui autorisent certains clients à se faire livrer directement et qui ne le font pas pour le reste de leurs clients.`, c'est bien ce que je fais. Une société = Un client ;)

**Comment by TBoileau** [comment]
A moins, que tu veuilles gérer cette option au niveau de l'utilisateur et non du client de manière globale

**Comment by lesateliersduroi** [comment]
C'est peut-être un souci de vocabulaire entre nous 2 mais je te confirme que cette option doit être gérer de manière circonstanciée pour chaque utilisateur.

**Comment by TBoileau** [comment]
ah ok
