### ISSUE TITLE
Front - Login

### ISSUE THREAD

**Issue by TimCarre** [TBoileau/key-privilege#185]
Resize automatique de la page de login en fonction de la résolution d'écran.

Capture d'écran de la page de login sur un écran de 1366 x 118 pixels.

![Capture d’écran 2021-04-23 à 18 09 10](https://user-images.githubusercontent.com/82883839/115899590-356b3980-a45f-11eb-9ac3-3cb3e20bb435.png)

**Comment by TBoileau** [comment]
ça veut dire quoi resize de la page en fonction de la résolution ? j'ai pris les dimensions de ta maquette.
Il aurait fallu le prévoir avant...Si sur un écran de 1366px ça ne passe pas, ça ne passe donc pas sur tous les écrans plus petits, sur quelles dimensions t'es-tu basé pour faire tes maquettes ?

**Comment by TBoileau** [comment]
Et pour les prochaines fois, pas besoin de créer d'issue, tu peux directement aller sur la [Pull Request](https://github.com/TBoileau/key-privilege/pull/184) qui concerne la page sur laquelle on va travailler.
