### ISSUE TITLE
Ajout du choix 196 produits par page, dans la boutique

### ISSUE THREAD

**Issue by Alessecco** [TBoileau/key-privilege#238]
Il manque le choix des 196 produits par page dans les options de filtre à droite de la page (je me réfère par rapport au PPT).

1.Aller sur la page 'Boutique'.
2. Cliquer sur le Dropdowns button '18 produits par page'.
3. Voir qu'il manque le choix des '196 produits par page'.

![Capture d’écran 2021-09-17 à 12 05 51](https://user-images.githubusercontent.com/90902151/133766745-6df8caa7-e898-42cc-8bf1-2e1d760a235c.png)

**Comment by TBoileau** [comment]
Il était présent avant mais on m'a justement demandé de l'enlever.

**Comment by Alessecco** [comment]
Très bien, je modifie le tuto pdf du coup.
