### ISSUE TITLE
Choix de son adresse de facturation impossible

### ISSUE THREAD

**Issue by Alessecco** [TBoileau/key-privilege#239]
Au moment où l'ont souhaite valider et commander nos articles dans le panier , on ne peut pas choisir notre adresse de facturation dans le cas où il y en a plusieurs.

1. Allez sur la page 'Boutique'.
2. Ajouter un article au hasard.
3.  Une fois l'article ajouté au panier, cliquer sur 'voir mon panier' ou aller sur la page 'Panier'.
4. Une fois sur la page 'Panier' , aucuns moyens de voir quelle est son adresse de facturation ni pouvoir choisir une autre adresse de facturation déjà enregistrée.

![Capture d’écran 2021-09-17 à 14 50 19](https://user-images.githubusercontent.com/90902151/133785197-baa9ef6f-1337-488e-aeeb-645718f91186.png)

**Comment by TBoileau** [comment]
On ne peut pas choisir d'adresse de facturation dans ce cas là.
