### ISSUE TITLE
1ère bannière sur la Home page, S en trop

### ISSUE THREAD

**Issue by Alessecco** [TBoileau/key-privilege#294]
Il y a un S en trop à Key Privilege sur la 1ère des bannières qui défile de la Home page.

![Capture d’écran 2021-10-26 à 10 50 54](https://user-images.githubusercontent.com/90902151/138844546-d9264cdb-a2fc-41e1-b501-4cd1fb903a96.png)
.

**Comment by TBoileau** [comment]
@Alessecco Cela vient de l'image, je n'ai donc pas la main dessus.
