### ISSUE TITLE
Formulaire SAV - 'Produit conerné'

### ISSUE THREAD

**Issue by Alessecco** [TBoileau/key-privilege#321]
**Décrire le bug**
Compte du super Admin : Sur le formulaire SAV le premier champ de saisie 'Produit concerné' ne fonctionne pas.

1. Aller sur la page 'Service après-vente' de Boutique.
2. Cliquer sur le bouton 'Demande de SAV'.
3. Premier champ de saisie 'Produit concerné' impossible d'écrire ou de choisir le produit depuis la flèche.

**Comportement attendu**
La flèche devrait pouvoir déroulé le nom des produits et/ou on pourrait directement écrire le nom du produit.

![Capture d’écran 2021-11-02 à 15 06 01](https://user-images.githubusercontent.com/90902151/139866562-a6cad39f-a336-4307-8506-0ecb6810199c.png)

![Capture d’écran 2021-11-02 à 15 20 50](https://user-images.githubusercontent.com/90902151/139866625-4e2e08f3-6a16-448d-82b0-e99abd125184.png)

**Comment by Alessecco** [comment]
Sur le compte du super Admin**

**Comment by TBoileau** [comment]
C'est normal car si tu regardes le contenu de la commande, elle est vide, aucun problème, par conséquent il n,'y a rien dans la liste déroulante
